### PR TITLE
Add bdd-style regression tests for spread plugin

### PR DESCRIPTION
**Pull request by benedictvh**
This is my first time collaborating using github, so hopefully things go smoothly!

I really like your plugins, and I want to do some more work on them (adding step functionality, for instance).  However, before I make any changes I want to implement regression testing to make sure I don't break anything.  I like the behaviour driven development approach, since it allows creating specification, documentation, and tests in the same file.

I used pytest-bdd to write a feature file and tests for the spread plugin.  I plan to write more tests, including for the other plugins, but I would like your feedback first.

I am not an experienced developer, so I welcome criticism.

One other thing: I was getting an error about using a relative import with no parent package when running my tests with pytest.  The error went away when I removed the "." from "from .common import x" in spread.py, but I not sure if that will create other problems.

### CODE REVIEW

**Comment by Akuukis** [comment]
Congratz on your first Pull Request!

Thank you for adding a test framework! Just like you, I also wish to continue those plugins but fear of regressions. This is a very welcome contribution.

I'm a developer but Python is not a language I'm experienced in, so it will take a while to review your PR, hopefully over the weekend.

**Comment by Akuukis** [comment]
@benedictvh Thank you for introducing me to Cucumber/Gherkin! It was a interesting read, and will be a good thing to have. For that I also researched the Zen of Python on how to organize tests, and other stuff about packages in general, so in the end reorganized the repo quite a bit. As part of that the package is renamed now - it used underscore instead of dash in it's name. I will move the repo after we merge your PR.

Overall, great PR for a necessary feature. Thank you!

Some concrete feedback:
1. move test files to `tests` folder, and import the package via `context.py` there. That's recommended by [Python docs](https://docs.python-guide.org/writing/structure/#test-suite)
2. for more concrete example case, rename "Simplest salary entry" to "Salary for June" or similar
3. for better clarity, rename "the following [..] transactions should be generated" to "generated entries should include the following [..] entries" or similar
4. Fix `pylint` warnings, e.g. use `_` for unused variables. In VSCode (check out the new workspace file) the warnings should show up automatically - if you use other IDE please commit workspace/settings file for yours too.
5. add `parsers.parse` also to `@where` case - see this [bug about VSCode's Cucumber extension and pytest-tdd](https://github.com/alexkrechik/VSCucumberAutoComplete/issues/318)
6. Please check `requirements.txt` and `Makefile` for anything I may have missed
7. If you know how to do it, please rebase to master instead of merge master for cleaner history

Some questions:
1. Why `pytest-tdd` and not, say, `behave`?

**Comment by benedictvh** [comment]
Thanks for the detailed feedback.  Stand by while I try to navigate this unfamiliar process!

To answer your question about why I chose pytest-bdd over other options: 

I actually have no experience with any of them, so I just looked to comparison articles and blog posts for recommendations.  I found [this article](https://blog.testproject.io/2019/05/16/python-testing-framework-pros-cons/) pretty thorough, and was convinced by the reasoning behind the author's reccomendation.  Beyond that, I have no skin in the game.

This is all experimental for me too, actually.  I learned about BDD in school, but have never had a chance to put it into practice.  Then, while trying to come up with test cases for your plugin, I decided I needed a clearer specification of the expected behaviour first, and it seemed like less work to just turn your examples into a specification and feed it directly into my test code.  BDD provides a clean way to do just that, so I decided to give it a shot.

**Comment by benedictvh** [comment]
So I am a little confused about what I need to do here.  I think we want your changes to come before my changes in the history, right?  So I need to fetch your changes, and then rebase my commits onto yours (after fixing issues you highlighted), then push everything?

Thanks for your help.

**Comment by Akuukis** [comment]
@benedictvh Yes, my changes is already in master, therefore your changes will come afterwards once we merge your branch.

The workflow with upstream/fork is a bit advanced, because you have to work with two remotes at the same time. Let me walk you through how I do that. First, check output of `git remote -v`, I guess it looks like this:
```
origin	git@github.com:benedictvh/beancount-interpolate.git (fetch)
origin	git@github.com:benedictvh/beancount-interpolate.git (push)
```
That `origin` is your *fork repository*, but not my *upstream repository*. When you do `git fetch` it will fetch from your fork, which is not updated, and thus won't fetch anything. You have to fetch from upstream, but first you need to add it with
```
git remote add upstream git@github.com:Akuukis/beancount-interpolate.git
git fetch --all
```
The `git fetch --all` which will fetch from all remotes instead of only `origin`, and you should see the updated master. Word "upstream" is arbitrary, feel free to use anything. Check `git remote -v` now, it should look like this:
```
origin	git@github.com:benedictvh/beancount-interpolate.git (fetch)
origin	git@github.com:benedictvh/beancount-interpolate.git (push)
upstream	git@github.com:Akuukis/beancount-interpolate.git (fetch)
upstream	git@github.com:Akuukis/beancount-interpolate.git (push)
```
To sync `master` of all three repos, I usually do like this:
```
git checkout upstream/master  # checkout upstream master as the truth...
git checkout -B master        # and recreate local master at this commit...
git push origin master -f     # and overwrite fork's master too.
git log -1                    # check if all master's are pointing to the same last commit.
```
Now, your local `master` should be up-to-date, and you can get to actual work! Either rebase your `test` branch to updated `master`, or start anew and copy what's useful from old branch via e.g. `git checkout tests -- src/spread.feature`.

**Pull request closed without merging**
