### PR TITLE
RFC: Version 3 architecture and features

### PR DESCRIPTION
**Pull request by benedictvh**
I am not sure if this is technically pull request material.  On the one hand, I do not have anything for you to merge, but on the other hand, I do have something for you to pull and take a look at.  Basically, I am partway through a major rewrite of your plugins, and wanted to share my changes and design rationale.

Why a major rewrite?  As I was trying to build a testing suite I ran into difficulties getting good test coverage.  Eventually, I realized that it would be less work to change the structure of the code to be more testable instead of writing test cases for the current design.  Furthermore, as I became more familiar with your code, I found various TODO's and places where you had left features unimplemented.  In trying to figure out how to implement those features, I came to the same conclusion: reworking the overall design could make future extensions far easier.

My motivation for this rewrite is therefore to increase testability, maintainability, and extensibility.  The design heritage between this version and your previous work is very strong, and when I am finished, I expect reasonable backwards compatability.  Below I will describe what I changed, what I kept unchanged, and what I have not yet implemented.

## Module structure
My first design goal was to create better module boundaries.  Reduced coupling makes unit testing far easier, and, provided the modules are well laid-out, makes adding new features less painful.  

The case of your `distribute_over_period` function best illustrates this point.  This is perhaps the most complicated piece of logic in the code, and represents a core algorithm, but I had a very hard trying to test it.  First of all, it calls parsing functions, so it dependant on syntax and parsing. Second, it takes the whole config object as an input, which made it hard for me to reason about it's output.  Third, it's output can even change based on the date the tests are run!  So I was having a terrible time trying to write test cases for it.  Moreover, I noticed that you had not fully implemented the step feature, and that you had unfinished plans to add different distribution styles (like exponential for example).   I suspected that in making the code more testable, I could make adding in those new features easier as well.

This case of `distribute_over_period` is just one example, but it illustrates the kind of problem I was trying to solve.  The solution was to rework the code into the following isolated areas of functionality:

1. Syntax parsing
2. Value distribution
3. Transaction generation

I was able to separate these areas by choosing the right kind of interface between them - low level and flexible - so that future changes will almost certainly require changing only a single module.  I believe that the interfaces themselves should never need to be touched.

### Parser
The parsing stage of course begins with a list of entries.  The Parser first separates the lists of entries into marked and unmarked.  This is done first so that the rest of the program has no chance of modifying an entry that it has no business with.  Then, for each marked entry, the Parser produces a lits of dates.  This is the entire interface with the distributor: a list of dates.  In fact, as far as the distributor is concerned, it could be a list of bananas; all the distributor does is take each element in the list and assign it a list of posting values, but more on that later.

Not only did this interface make testing the parser trivial, it will also make adding new features much easier.  As proof of this, I was able to fully implement the step feature in the parser only, by changing the list of dates it outputs.  The rest of the code just worked.  In the future, creating syntax extensions that allow a transaction to recur e.g. on Mondays and Thursdays of odd numbered months during the waxing phase of the moon will be as simple as adding new syntax: the interface to the distributor is low-level enough to handle arbitrarily complex sequences.

### Distributor
The inputs to the distributor are a vector of posting values and a list of dates:
```
dates = [date 1, date 2, date 3 ... date N]
posting_values = [
    posting_value 1, 
    posting_value 2,
    posting_value 3,
     ...
    posting_value M
]
```

The distributor uses the posting-values vector to create a new vector for each date, producing a matrix like so:

```
                date 1    date 2   date 3    ...  date N
posting_value 1    v11       v12       v13   ...     v1N
posting_value 2    v21       v22       v23   ...     v1N
posting_value 3    v31       v32       v33   ...     v1N
 ...               ...       ...       ...   ...     ...
posting_value M    vM1       vM2       VM3   ...     VMN
```
Different types of distributions will produce different values for the matrix, but otherwise the output is the same.  For example, the `duplicate_over_period` function you wrote for the recur plugin simply copies the posting values to each date.  Creating an exponential distribution function will be trivial. 
The only other input to the distributor is the `min_value` configuration option (not yet implemented), which means testing is straightforward.

### Generator
The generator takes a matrix of posting values and produces a posting for each value and a transaction for each date.  The generator is responsible for making sure that no postings are generated with dates that are in the future.  It also takes inputs relating to output style, like the suffix to append to the narration.  Much of the user configuration options should affect this module only, which will make writing test cases for the other modules easier.

## Posting-level marks
After a _lot_ of thought, I decided to get rid of posting level marks.  It is just so useful to have a single mark to parse for each transaction, instead of getting a different list of dates to distribute for each posting!  If you want really have to spread different postings in a transaction over a different periods, you will just have to break the transaction into separate transactions with different marks.  I figured this is acceptable, since it is probably a pretty rare usecase.  Large parts of my design rely on this change, so I really hope you find it acceptable.  Since we still need a way to specify which to postings to spread or depreciate, my plan is to have it work with tags like so:
```
2020-01-01 * "TheCompany" "Paycheque"
    spread: "Month @ 2020-01-01"
    Income:TheCompany:Wages             -1000.00 CAD #spread
    Income:TheCompany:Vacation-Pay   -40.00 CAD #spread
    Expenses:Pension-Contributions         10.00 CAD          ; <- don't spread this one
    Assets:Chequing
```
Or with metadata (allowing you to specify a spread account),  like so:
```
2020-01-01 * "TheCompany" "Paycheque"
    spread: "Month @ 2020-01-01"
    Income:TheCompany:Wages             -1000.00 CAD
        spread: "Assets:Unpaid-Earnings:Wages"
    Income:TheCompany:Vacation-Pay   -40.00 CAD #spread
    Expenses:Pension-Contributions         10.00 CAD            ; <- don't spread this one
    Assets:Chequing
```

## Single plugin structure
This is the probably the biggest change I made to the program in terms of usage.  Hopefully it is not too controversial.  I consolidated all 4 plugins into a single "interpolate" plugin, and now refer to what were previously different "plugins" as different "commands".  The way in which transactions are marked remains unchanged.

The decision to consolidate was born out of a different kind of frustration: creating different test suites for different plugins that tested the same code, and having to update the same code in multiple places after a change.  I think this is the direction you were headed in anyway, since I saw in the commit history you had been trying to isolate out common code for a while.  With the degree of functionality shared between the plugins, I think a single plugin structure makes more sense.  In fact, I was even able to implement the spread "command" using the split function, after I noticed that a spread is basically just a split with one extra entry generated.

## Syntax
I added one feature that is essential for me.  I have been using your plugins to accrue my bill expenses over billing periods, and some of my bills have variable length periods, and the periods are reported on my bills with a start and end date rather than a number of days.  So, I updated the syntax to allow specifying an end date instead of a duration: `split: "month @ 2020-04-01"` and `split: "2020-04-30 @ 2020-04-01"` now do the same thing.  It is a bit awkward having to specify the end date before the start date, but at least it ensures backwards compatibility.

Other than that I left the basic syntax unchanged, but I would like to propose a somewhat different direction with respect to configuration.  It seems like a major focus of your previous work was to allow specifying behaviour with as little typing as possible by making use of configurable defaults.  For example, you made it so a transaction can be spread or split with an empty mark, or even just a tag, by falling back on a default duration, date, and step.  Although this can be really nice if you mostly spread your transactions the same way and want to decrease clutter in your beancount file and maybe reduce the amount of typing needed, to me it seems to have some disadvantages as well.  Some people might think that having the full `command: "duration @ start "` mark makes transactions in the beancount file look ugly, but I find it also helps identify them as a different kind of transaction from the rest, i.e. one that will be modified by a plugin.  Furthermore, the more the parser depends on configurable inputs outside of the mark, the more complicated it is to specify test cases.  One of Martin Blais's design goals for beancount, according the docs, was actually to minimize configurability, and after thinking more about testability and maintainability, I think I see why. 
 However, I am perhaps biased with respect to this feature because I personally do not mind putting the full mark on my transactions.  Please let me know what you think.

There are also aspects of the original syntax that I plan to implement but haven't yet, like specifying a start date using only the year and month.

## Plain pytest instead of pytest-bdd
This might be temporary, but while trying to follow test-driven-developement procedures by writing tests and then coding to pass the tests, I noticed that writing gherkin and step definitions was really slowing me down.  For early developement purposes on a team of one, being able to quickly write new tests seemed more important than having self-documenting behavioural specification.  I used pytest to create integration tests using a single beancount file as input and a single beancount file to compare output.  Creating a new test case was as easy as writing a new input transaction in the input file and the proper output transactions in the output file.  If it seems like BDD will be is more usefull later it will be easy to switch back, but for now pytest-bdd seems a bit too cu-cumbersome.  Hah.

### Housekeeping
I apologize for the current state of my code.  I have put in almost no comments, and many functions still need to be refactored.  There is also no usefull commit history to speak of.  I need to work on my git habits, because in the early phases of development I usually end up forgetting I am even in a git repository.

### Configuration and command aliases
My plan is to implement configuration last.  One drawback of moving to a single plugin structure is that configuration on a "per-command" basis becomes more complicated.  I think that for many of the configuration options that you had implemented, per-command configuration is unnecessary.  For example, although I could be missing something, I don't see much reason why anybody would want to configure a separate `max_new_transactions` for each command.  If necessary, per-command configuration is still possible with more complicated JSON strings.

### Spread and depreciate plugins
I plan to implement the depreciate command after the spread command is finished, but I have more work to do on the spread plugin first.

### Metadata behaviour
I need to implement consistent behaviour with respect to posting and transaction level metadata.  I think the plugin should remove all mark and tag metadata that is intended for the use by the plugin, but keep copy other metadata to the generated postings and transactions.  I am not sure if this was implemented fully in the original codebase either.

### Distributor cannot handle postings with different currencies
Right now, the distributor works with decimal numbers instead of `Amount`s, so it balances transactions as if every posting has the same currency.  This is a major piece of missing functionality that I have not yet started, however, I believe the solution will be fairly straightforward.

### Testing
I so far implemented testing only to the extent that it helps me write code. I plan to implement testing to a higher standard, and revisit the idea of BDD, after I have done more development work.

### Miscelaneous
Lots of little things, like tags on generated transactions.

## Summary
I am very proud of the work I have done, and although I am sure you will have many concerns, I hope you find my general approach is reasonable.  Either way, I had a lot of fun and learned tons.

I look forward to hearing your thoughts.  Please do not think I am expecting you to match my verbosity!  Not everybody has as much time on their hands as I do right now.

Good luck and stay safe as the pandemic continues to unfold.

- Benedict

### CODE REVIEW

**Comment by Akuukis** [comment]
Wow. I was starting to wonder where you've gone, but looks like that you were very busy!

Overall, I can only assure you that you understand both my code and between the lines too. Furthermore I agree that it can be so much more, and your efforts are in the right direction. Thank you!

On the other hand, it will take a while to go over and review. What worries me is having that as one big refactor, instead of many smaller ones, as well lack of tests to confirm backward compatibility. Give me the weekend to look into it!

**Comment by Akuukis** [comment]
By the way, these type of issues/PRs/forks are called RFCs (Request for Comments). For a RFC this is great - everything is nicely described, and code is just good enough to see what you mean by it. Thanks!

Ok, let's jump into details.

## Module structure

I love it.

Yeah, that's it - you've already explained everything yourself.

## Posting-level marks

In fact, I'm using it myself. Here's a simplified example how that's useful:
```
2020-04-05 * "IKEA" "Spring shopping"
    Assets:Fixed:Goods     250.00 EUR  ; solid closet
        depr: "3600"
    Assets:Fixed:Goods      50.00 EUR  ; shoddy chair
        depr: "Year"
    Expenses:Supplies       20.00 EUR  ; household chemicals
        spread: "Month"
    Expenses:Food:Snacks     0.39 EUR  ; that awful hotdog
    Assets:Cash
```

I recently checked numbers and this plugin is downloaded like 100-200/month, out of 1500-2000/month downloads of beancount itself. On one side that's wonderful to know that almost 10% of beancounters use this plugin, but on the other side it gives a compatibility burden. We don't know whenever this feature is used by one person (me) or by majority of them, therefore I am super-hesitant to throw out an existing working feature.

I don't see obvious problems with supporting it. Let me know what problems there are and we will figure something out.

## Single plugin structure

Sounds fair, but would be a breaking change. Let's see if we can keep the old way but as a alias to the new way, so that is not a breaking change.

## Syntax

That's a solid feature, sometimes I also need it but work around it somehow.

Yes, I'm using a lot of defaults to reduce clutter and configurability. I believe that having sane defaults and lot's of shortcuts are soft-enforcing less configuration. Here's how it works for me - I use the short versions a lot, like 95% of entries. When time comes where short version is not sufficient, I dig up README and carefully write the long version, and sometimes even leave a comment why so. But some other times, I just don't and after a little though it turns out that a short version actually works good enough. Furthermore I believe it helps to learn and get started by not enforcing complexity, but as a author I can't really judge this argument.

On the other hand, if you prefer explicitly and verbosity, just do it your way. I like this plugin is flexible.

Back to your case, overloading `command: "duration @ start "` with `command: "end @ start "` doesn't feel obviously right. Perhaps let's expand the syntax like this: `command: "duration @ start to end"`. That way, I'm theorizing, we could simplify configuration and get rid of `spreadBefore` commands, as well keep straightforward shortcuts in all combinations (all examples equal):
- `month @ 2020-04-01`
- `month to 2020-04-30`
- `2020-04-01 to 2020-04-30`
- `month @ 2020-04-01 to 2020-04-30` (works as assertion, for tx generators and explicit people)

A question for you: would defaulting `start` to the date of transaction makes sense for 80%+ cases? If not, what then?

In either case, I'd prefer not to clutter the upcoming already big change with also this feature, which can totally be done as a separate next step.

## Plain pytest instead of pytest-bdd

If simple unit tests help you along the way, sure, write and commit them. But in the end, let's stick to gherkin. I understand that during exploratory phase to make this RPC well-made tests are cumbersome, but they are so much better for end user, because the user has plenty (official and working) examples to learn from.

## Summary

This is a huge change, it needs to be broken down into separate sequential steps. Here's a great blog that wrote on [why rewriting whole code is bad](https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/). Furthermore for the 10% of beancount community we should not break anything, and provide deprecation paths/warnings where needed.

Here's a plan how to prepare to get all of this into master:
1. add single plugin structure, but keep the separate plugins for now. Don't document nor announce the single plugin structure, yet.
2. rewrite separate plugins as a aliases for single plugin structure, and add some tests to make sure nothing has been broken.
3. add plenty of gherkin tests via the single plugin structure to make sure we don't break anything.
4. refactor module structure.
5. (so far for the user nothing has changed, but we are finally ready to write features confidently)
6. release and bump major version with notice to users about "hopefully nothing's broken, and by the way the metadata for generated entries are undefined and will change any time", because we can't really guarantee that nothing's broken. This will allow people to revert to older version and use to hotfix it separately, as well give time for them to start reporting bugs while we write the next features.

Then, effectively in any order, let's get the features in, and bump the minor version with each of them.
- syntax for `end` date
- multi-currency support
- sort out the metadata for generated entries
- etc.

Thanks, looking forward to your reply.

**Comment by benedictvh** [comment]
Yeah, I agree.  Smaller changes are always preferable.  If you want, you can wait for me to put more comments in first so the code is easier to understand before you take a look at it.  That might save you some time.

**Comment by benedictvh** [comment]
Oh wow, I had no idea the plugins were that popular!  That's really cool, but I understand how it places a burden of responsibility on the developers.

For some reason, I imagined there were only a handful of users.  Maybe because whenever I see a repository with only one contributor, I assume that not many people know about it.  I guess there is no reason in principle why a repository couldn't have hundreds of thousands of users and only one contributor.

That's actually really motivating.  I was hoping to contribute to your code because I use it myself, and to gain some experience with open source, but eventually I really wanted to create something that would see widespread use.  Knowing that such a large chunk of the beancount community uses your plugins makes it that much more fun.

Those are fair points about the posting level syntax change, and I see how even I might use the feature now.

I have some other stuff to do today, but I will get back to you with a more complete reply soon.

**Comment by benedictvh** [comment]
First of all, I take your points re posting level marks and configurable defaults, and I am fine to continue with your approach.  I was having fun trying to create as clean and tidy an architecture as possible, but you can only reduce complexity so much before you lose out on functionality, and you make a good case for the importance of the functionality in question.

Second, I like how you distinguish between changes that are structural, and changes that are functional.  If I could do it again, I would create an RFC for the single plugin and module structure only.  Like your article described, rewriting code is fun, and it is easy to get carried away.

With respect to your development plan, I have some questions about steps 1 and 2:

> 1. add single plugin structure, but keep the separate plugins for now. Don't document nor announce the single plugin structure, yet.

So after this step, we should still have split.py, spread.py, etc., but they would just be wrappers for functions defined in interpolate.py?  Is that what you mean by adding the single plugin structure but keeping plugins separate?  Are we merging into master at this point, or working on a developement branch?

> 2. rewrite separate plugins as a aliases for single plugin structure, and add some tests to make sure nothing has been broken.

Does this step break importing the plugins separately?  Or is the goal to try to make sure that the users never have to change that at all?  Could you explain more how the aliasing would work?

Any more detail would be appreciated.  I want to make sure I understand exactly what you want before I start working.  Thanks for your help.

**Comment by Akuukis** [comment]
Yes, that's great idea - the best next step would be to create another RFC or even a proper pull request for the structural changes only, so we can focus on first things first. You understand right by calling them wrappers, that's a more accurate term in this case than an alias. The difference between point 1 and 2 is that
- in first point, just create the single `interpolate.py` so we can focus discussion on how it looks like (and ofc it will have a lot of duplicating stuff from other four), and then, yes, we merge it to master. 
- afterwards in the 2nd PR we can focus review on the wrappers, tests and compatibility. The aim is that users don't have to do anything for now. It's ok to have all the new features in the `interpolate.py` only.

If everything's clear just close this RFC and let's meet at the next one!

**Pull request closed without merging**
