### PR TITLE
Single-plugin configuration handling and regression testing

### PR DESCRIPTION
**Pull request by benedictvh**
### Single plugin configuration
I came up with syntax and semantics for configuration in single plugin mode (using a single config string).  The difference is that options can now be either global or command specific.  Global options are defined at the top level, whereas command specific options are defined within nested object, like so:
```
plugin beancount_interpolate "{
    'global_option_1': value1,
    'global_option_2': value2,
    ...
    'command1': {
        'command_specific_option_1': value_3,
        'command_specific_option_1': value_4,
         ...
     }
     'command_2': {
         ...
     }
}
```
When the same option is defined globablly and specific to a command, command specific options have precedence.

This design has the advantage that the size and complexity of the config string is proportional to the complexity of the configuration needed.  Using just the defaults still uses an empty config string.  Changing only a few options that apply to all plugins results in a simple config string:
```
plugin beancount_interpolate "{
    'min_value': 0.10,
    'default_step': 'Week'
}
```
This is actually less verbose than it was before, when a config string was needed for each plugin loaded even if the option was the same.

Verbosity will become unavoidable only as complexity increases:
```
plugin beancount_interpolate "{
    'min_value': 0.10,
    'default_step': 'Week',
    'recur': {
         'default_step': 'Day',
         'tag': 'recurreded'
     }
     'spread': {
         'tag': 'spreadereed',
         'account_assets': 'Assets:Right-Now',
         'default_duration': 'Month'
    }
}
```
I think loading all commands by default should be fine for most users.  The only reason I can think of is that there is a metadata key conflict, which they could solve by aliasing.  If for some reason a user does not want a command, we could have a command specific option like:
```
plugin beancount_interpolate "{
    'recur': {
         'disable': True
     }
}
```
This can all be changed going forward as well.

### Multi plugin configuration
Still works.  The wrappers just convert the options given into command specific options.
 For example, a spread plugin configuration.
```
{
    'default_duration': 'Week',
    'tag': 'Spreadedred',
    'account_assets': 'Assets:Right-Now'
}
```
Becomes a spread command configuration
```
{
    'spread': {
        'default_duration': 'Week',
        'tag': 'Spreadedred',
        'account_assets': 'Assets:Right-Now'
    }
}
```
That way the functions in `interpolate.py` work with the same format regardless.

### Regression testing

I added gherkin tests for the configuration options.  I have pretty good test coverage now, but I have more tests to write.

The tests run on the multi plugin structure by default, but they can be run using the wrappers by passing a custom pytest option defined in `conftest.py`.
```
pytest --multiPluginMode
```
 used if statements in the step definitions to allow both structures to be tested.  It is a big ugly, but it can all be cleaned up once support for the multi plugin structure is no longer necessary.

The tests all pass for me in multi plugin mode but not single plugin mode, which is expected because the single plugin structure is unfinished anyway.

### Terminology

Although I have been referring to what were previously different plugins as commands in the single plugin code, I am not invested in that terminology at all.  If you want something different, I can easily make the change.

Similarly, I have been using `txn` as an abbreviation in my code instead of `tx`, but that was just due to an accidental misreading of your code when I first started contributing.  Up until now I have been changing your code to match mine when necessary, but I could easily switch my code to match what was there before.

### CODE REVIEW

**Review by Akuukis — COMMENTED** [review]
@benedictvh Great overall, but two easy to solve problems:

1. not supporting `max_new_tx` is a breaking change. I understand that Blais uses `txn` instead of `tx` and that's a fine direction. So, please, do either
    - revert to `max_new_tx`
    - support both and print deprecation warning for `max_new_tx` variant.


2. please configure your IDE to deal with trailing whitespaces. `config_options.feature` is full of those, and they are also elsewhere. I'm using VSCode with a workspace file `.vscode/beancount_interpolate.code-workspace` that has a recommended plugin `shardulm94.trailing-spaces` which does the job (I will configure it to trim-on-save also).

**Comment by benedictvh** [comment]
I am using emacs, which has a built in whitespace-mode that you can switch on.  Although it makes trailing whitespace easy to find, it unfortunatey also shows non-trailing whitespace (in a less ovbious colour), meaning it is too annoying to keep on during normal code editing.  For now, I can remember to switch it on for each file and manually remove trailing whitespace before I commit.  I will look into other options when I have more time.

I have also been working on module restructuring, but I am moving to a different city in a couple days and things have been very busy, so it might be a few weeks before I can get another pull request up.

**Comment by Akuukis** [comment]
Hi @benedictvh , how are you doing?

**Comment by benedictvh** [comment]
Not too bad @Akuukis, thanks.  Just been very busy - first with the move and then getting used to a new house, new job, new city, etc.  All with 3 small children.  I really hope to have some time in the next couple weeks to get back to contributing.  I certainly have not lost interest.

**Comment by benedictvh** [comment]
Hello @Akuukis, I want to let you know why I haven't been active and what that means going forward.  

I started contributing last winter when I was looking for work, and then when the pandemic hit I had plenty of free time to devote to coding.  However, when I started working again in the summer, I realized just how little energy I have leftover after balancing the demands of work and family.  Although I hope to make room in my life for projects like this in the future, I do not know whether that will happen in a couple months, a year, or longer.

I still want to tell myself that I will be able to find some time in the a week or two, but if I am being honest that is extremely unlikely, so don't hold out for me.

**Comment by Akuukis** [comment]
Thanks @benedictvh for reaching out! It's great that you have a work and family, and I appreciate you being honest. Furthermore, now this is clearly free to pick up by others.

By the way, I'm already making progress nearby - https://github.com/Akuukis/beancount_share

Happy Christmas and a boring New Year ;)

**Comment by Akuukis** [comment]
I'm about to backport a lot of good stuff I've learned while writing the other plugin, but it will make this PR out-of-date. Therefore I will close it and instead document your started work in the [README here](https://github.com/Akuukis/beancount_interpolate#development).

**Pull request closed without merging**
